my_string=input()
print("количество символов", len(my_string))
print(my_string.upper())
print(my_string.upper().lower())
print(my_string.replace(' ', ''))
print("Первый символ фразы", my_string[0])
print("Последний символ фразы", my_string[-1])